import React, { createContext, useState, useContext, useEffect } from 'react';
import * as SecureStore from 'expo-secure-store';

const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    searchTrains: 'Search Trains',
    lostFound: 'Lost & Found',
    suggestions: 'Suggestions',
    profile: 'Profile',
    todayTrips: "Today's Trips",
    followedTrains: "Followed Trips",
    liveFeed: "Live Feed",
    trackLive: "Track Live",
    active: "Active",
    noActiveTrips: "No active trips today",
    noFollowedTrips: "You are not following any trips",
    noUpdatesFeed: "No updates in the feed",
    myStatus: "My Status",
    gpsMapPin: "GPS Pin",
    InTransit: "In Transit",
    OnTime: "On Time",
    Delayed: "Delayed",
    Cancelled: "Cancelled",
    Arrived: "Arrived",
    Scheduled: "Scheduled",
    Ended: "Ended",
    Logout: "Logout",
    welcome: "Welcome",
    Search: "Search",
    byTrain: "By Train Number",
    byRoute: "By Route",
    origin: "Origin Station",
    destination: "Destination",
    selectStation: "Select Station",
    searchPlaceholder: "Enter Train Number (e.g. 903)",
    trainNumber: "Train Number",
    trains: "Trains",
    details: "Details",
    allTrips: "All Trips",
    followPlan: "Follow Plan",
    createPlan: "Create Follow Plan",
    editPlan: "Edit Follow Plan",
    noFollowPlan: "No recurring follow plan",
    leadTime: "Alert Lead Time",
    role: "Role",
    passenger: "Passenger",
    follower: "Follower",
    save: "Save",
    delete: "Delete",
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    daysFull: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    emptyChairs: "Empty Chairs",
    fullChairs: "Full Chairs",
    aisleCrowded: "Aisle Crowded",
    crowded: "Crowded",
    empty: "Empty",
    atStation: "At Station",
    speed: "Speed",
    stopsRemaining: "Stops Remaining",
    liveTracking: "Live Snapped Tracking Active",
    passengerMode: "Passenger Mode (Share GPS)",
    shareUpdate: "Share Train Update",
    writeUpdate: "Write an update...",
    submit: "Submit",
    thanks: "Thanks",
    deleteReport: "Delete",
    startPrompt: "Has this trip started?",
    endPrompt: "Has this trip ended?",
    yes: "Yes",
    no: "No",
    reCenter: "Re-center Map",
    routeStops: "Route Timetable",
    crowdLevel: "Crowd Level",
    statusTag: "Status Tag",
    welcomeBack: "Welcome Back",
    signInSubtitle: "Sign in to track your trips in real time",
    emailAddress: "Email Address",
    password: "Password",
    signIn: "Sign In",
    createAccount: "Create Account",
    signUpSubtitle: "Get started with Egypt's premium train updates",
    confirmPassword: "Confirm Password",
    displayName: "Display Name",
    alreadyHaveAccount: "Already have an account? Sign In",
    dontHaveAccount: "Don't have an account? Register",
    register: "Register",
    emailPlaceholder: "name@example.com",
    namePlaceholder: "Your Name",
    lost: "Lost",
    found: "Found",
    createPost: "Create Post",
    postDetails: "Post Details",
    title: "Title",
    description: "Description",
    contactInfo: "Contact Info",
    imageUrl: "Image URL (Optional)",
    resolved: "Resolved",
    comments: "Comments",
    writeComment: "Write a comment...",
    addComment: "Add Comment",
    coordinates: "Coordinates",
    mapInstruction: "Tap the map or drag the marker to set coordinates automatically.",
    submitStop: "Submit Stop Suggestion",
    city: "City",
    selectGov: "Select Governorate",
    nameEn: "English Name",
    nameAr: "Arabic Name",
    close: "Close",
    lostFoundSubtitle: "Report and recover lost items on trains",
    all: "All",
    Users: "Users",
    accountSettings: "Account Settings",
    displayName: "Display Name",
    bio: "Bio",
    bioPlaceholder: "Tell us about yourself...",
    changePhoto: "Change Photo",
    takePhoto: "Take Photo",
    chooseFromLibrary: "Choose from Library",
    cancel: "Cancel",
    upcomingTrips: "Upcoming (Next 24h)",
    noUpcomingTrips: "No upcoming trips scheduled.",
    tripHistory: "Trip History",
    noTripHistory: "No previous trip logs found.",
    to: "To",
    train: "Train",
    profilePicture: "Profile Picture",
    permissionDenied: "Permission Denied",
    profileUpdated: "Profile updated successfully!",
    profilePicUpdated: "Profile picture updated successfully!",
    unfollowTrip: "Unfollow Trip",
    unfollowConfirm: "Are you sure you want to unfollow this trip?",
    unfollow: "Unfollow",
    cancelPlan: "Cancel Plan",
    cancelPlanConfirm: "Are you sure you want to delete this follow plan?",
    Error: "Error",
    Success: "Success",
    Warning: "Warning",
    Completed: "Completed",
  },
  ar: {
    home: 'الرئيسية',
    searchTrains: 'بحث القطارات',
    lostFound: 'المفقودات',
    suggestions: 'المقترحات',
    profile: 'الملف الشخصي',
    todayTrips: 'رحلات اليوم',
    followedTrains: 'الرحلات المتابعة',
    liveFeed: 'البث المباشر',
    trackLive: 'تتبع مباشر',
    active: 'نشط',
    noActiveTrips: 'لا توجد رحلات نشطة اليوم',
    noFollowedTrips: 'أنت لا تتابع أي رحلات',
    noUpdatesFeed: 'لا توجد تحديثات',
    myStatus: 'حالتّي',
    gpsMapPin: 'موقع GPS',
    InTransit: 'في الطريق',
    OnTime: 'في الموعد',
    Delayed: 'متأخر',
    Cancelled: 'ملغي',
    Arrived: 'وصل',
    Scheduled: 'مجدول',
    Ended: 'منتهي',
    Logout: 'تسجيل الخروج',
    welcome: 'مرحباً',
    Search: 'بحث',
    byTrain: 'رقم القطار',
    byRoute: 'خط السير',
    origin: 'محطة القيام',
    destination: 'محطة الوصول',
    selectStation: 'اختر المحطة',
    searchPlaceholder: 'أدخل رقم القطار (مثال: 903)',
    trainNumber: 'رقم القطار',
    trains: 'القطارات',
    details: 'التفاصيل',
    allTrips: 'جميع الرحلات',
    followPlan: 'خطة المتابعة',
    createPlan: 'إنشاء خطة متابعة',
    editPlan: 'تعديل خطة المتابعة',
    noFollowPlan: 'لا توجد خطة متابعة متكررة',
    leadTime: 'وقت التنبيه المسبق',
    role: 'الدور',
    passenger: 'راكب',
    follower: 'متابع',
    save: 'حفظ',
    delete: 'حذف',
    days: ["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    daysFull: ["الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    emptyChairs: 'مقاعد شاغرة',
    fullChairs: 'مقاعد ممتلئة',
    aisleCrowded: 'الممر مزدحم',
    crowded: 'مزدحم جداً',
    empty: 'فارغ',
    atStation: 'في المحطة',
    speed: 'السرعة',
    stopsRemaining: 'المحطات المتبقية',
    liveTracking: 'التتبع المباشر النشط',
    passengerMode: 'وضع الراكب (مشاركة الـ GPS)',
    shareUpdate: 'مشاركة تحديث للقطار',
    writeUpdate: 'اكتب تحديثاً...',
    submit: 'نشر',
    thanks: 'شكراً',
    deleteReport: 'حذف',
    startPrompt: 'هل بدأت الرحلة؟',
    endPrompt: 'هل انتهت الرحلة؟',
    yes: 'نعم',
    no: 'ليس بعد',
    reCenter: 'إعادة توسيط الخريطة',
    routeStops: 'جدول المحطات',
    crowdLevel: 'مستوى الازدحام',
    statusTag: 'حالة القطار',
    welcomeBack: 'مرحباً بعودتك',
    signInSubtitle: 'سجل الدخول لتتبع رحلاتك في الوقت الفعلي',
    emailAddress: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    createAccount: 'إنشاء حساب',
    signUpSubtitle: 'ابدأ الآن مع تحديثات القطار المتميزة في مصر',
    confirmPassword: 'تأكيد كلمة المرور',
    displayName: 'الاسم الظاهر',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟ سجل الدخول',
    dontHaveAccount: 'ليس لديك حساب؟ سجل الآن',
    register: 'تسجيل',
    emailPlaceholder: 'name@example.com',
    namePlaceholder: 'الاسم الكامل',
    lost: 'مفقود',
    found: 'معثور عليه',
    createPost: 'إضافة بلاغ',
    postDetails: 'تفاصيل البلاغ',
    title: 'العنوان',
    description: 'الوصف',
    contactInfo: 'معلومات الاتصال',
    imageUrl: 'رابط الصورة (اختياري)',
    resolved: 'تم العثور/الحل',
    comments: 'التعليقات',
    writeComment: 'اكتب تعليقاً...',
    addComment: 'إضافة تعليق',
    coordinates: 'الإحداثيات',
    mapInstruction: 'اضغط على الخريطة أو اسحب العلامة لتحديد الإحداثيات تلقائياً.',
    submitStop: 'تقديم مقترح المحطة',
    city: 'المدينة',
    selectGov: 'اختر المحافظة',
    nameEn: 'الاسم بالإنجليزية',
    nameAr: 'الاسم بالعربية',
    close: 'إغلاق',
    lostFoundSubtitle: 'أبلغ واستعد المفقودات على القطارات',
    all: 'الكل',
    Users: 'مستخدمين',
    accountSettings: 'إعدادات الحساب',
    displayName: 'الاسم الظاهر',
    bio: 'نبذة عنك',
    bioPlaceholder: 'أخبرنا عن نفسك...',
    changePhoto: 'تغيير الصورة',
    takePhoto: 'التقاط صورة',
    chooseFromLibrary: 'اختيار من المعرض',
    cancel: 'إلغاء',
    upcomingTrips: 'الرحلات القادمة (24 ساعة)',
    noUpcomingTrips: 'لا توجد رحلات قادمة مجدولة.',
    tripHistory: 'سجل الرحلات',
    noTripHistory: 'لا توجد سجلات رحلات سابقة.',
    to: 'إلى',
    train: 'قطار',
    profilePicture: 'صورة الملف الشخصي',
    permissionDenied: 'تم رفض الإذن',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    profilePicUpdated: 'تم تحديث صورة الملف الشخصي بنجاح!',
    unfollowTrip: 'إلغاء متابعة الرحلة',
    unfollowConfirm: 'هل أنت متأكد أنك تريد إلغاء متابعة هذه الرحلة؟',
    unfollow: 'إلغاء المتابعة',
    cancelPlan: 'إلغاء الخطة',
    cancelPlanConfirm: 'هل أنت متأكد أنك تريد حذف خطة المتابعة هذه؟',
    Error: 'خطأ',
    Success: 'نجاح',
    Warning: 'تحذير',
    Completed: 'مكتمل',
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState('en');

  useEffect(() => {
    const loadLocale = async () => {
      try {
        const stored = await SecureStore.getItemAsync('locale');
        if (stored) {
          setLocale(stored);
        }
      } catch (e) {
        console.error('Failed to load locale', e);
      }
    };
    loadLocale();
  }, []);

  const changeLanguage = async (lang) => {
    setLocale(lang);
    try {
      await SecureStore.setItemAsync('locale', lang);
    } catch (e) {
      console.error('Failed to save locale', e);
    }
  };

  const t = (key) => {
    if (translations[locale] && translations[locale][key]) {
      return translations[locale][key];
    }
    return key;
  };

  const isRTL = locale === 'ar';

  return (
    <LanguageContext.Provider value={{ locale, t, isRTL, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
